server:
  port: 8003
spring:
  application:
    name: eureka-provider-demo
# Eureka 配置
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}:${server.port}  # 主机名，不配置会获取系统主机名
    prefer-ip-address: true # 是否使用IP注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 实例ID
  client:
    register-with-eureka: true # 是否将自己注册到注册中心，默认true
    fetch-registry: true # 是否从注册中心获取注册信息，默认true
    service-url: # 指向注册中心
      defaultZone: http://root:123456@localhost:8002/eureka/,http://root:123456@localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: shutdown  # 开启shutdown端点访问
  endpoint:
    shutdown:
      enabled: true  # 开启shutdown优雅停服
